services:
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      POSTGRES_USER: odoo18
      POSTGRES_PASSWORD: odoo18
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo18"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    build: .
    container_name: odoo18
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      HOST: db
      PORT: 5432
      USER: odoo18
      PASSWORD: odoo18
    volumes:
      - odoo18-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
    networks:
      - odoo-network
    restart: always

volumes:
  odoo18-db-data:
  odoo18-data:

networks:
  odoo-network:
    driver: bridge
